"""Internal entity id -> friendly DisplayName for the viewer's
Other-Requirements value resolution (boons/traits, keepsakes, companions,
weapon aspects, god boons, enemies, cosmetics, items and more).

Vendored from Hades 1's ``Game/Text/en`` sjson DisplayName entries,
filtered to the ids that appear as ``otherRequirements`` operand values.
Regenerate with ``scripts/gen_entity_names.py --write`` after a data
refresh; the internal id is always kept in the row tooltip, so a missing
entry just falls back to showing the raw id.
"""

HADES1_ENTITY_NAMES = {
    "Achilles": "Achilles",
    "AchillesPatroclusAssistTrait": "Companion Antos",
    "AchillesPatroclusQuestItem": "Hero's Sacrifice",
    "AmmoBoltTrait": "Lightning Rod",
    "AphroditeUpgrade": "Aphrodite",
    "AresHomingTrait": "Hunting Blades",
    "AresUpgrade": "Ares",
    "ArtemisBonusProjectileTrait": "Mirage Shot",
    "ArtemisReflectBuffTrait": "Deadly Reversal",
    "ArtemisUpgrade": "Artemis",
    "Asphodel": "Asphodel",
    "AsphodelReprieve": "Fountain Chamber, Asphodel",
    "AthenaUpgrade": "Athena",
    "AutoRetaliateTrait": "Vengeful Mood",
    "BackstabAlphaStrikeTrait": "Black Shawl",
    "BlastCubeFused": "Urn of Shadows",
    "BlizzardOrbTrait": "Blizzard Shot",
    "BloodlessGrenadier": "Inferno-Bomber",
    "BloodlessGrenadierElite": "Dire Inferno-Bomber",
    "BloodlessNaked": "Bloodless",
    "BloodlessNakedBerserker": "Bone-Raker",
    "BloodlessPitcher": "Burn-Flinger",
    "BloodlessPitcherElite": "Dire Burn-Flinger",
    "BloodlessSelfDestruct": "Slam-Dancer",
    "BloodlessWaveFist": "Wave-Maker",
    "BloodlessWaveFistElite": "Dire Wave-Maker",
    "BossAddGems": "Vanquisher's Keep",
    "BowBondTrait": "Aspect of Rama",
    "BowLoadAmmoTrait": "Aspect of Hera",
    "BowMarkHomingTrait": "Aspect of Chiron",
    "BowWeapon": "Heart-Seeking Bow",
    "BreakableValue1": "Urns of Wealth, Lesser",
    "BreakableValue2": "Urns of Wealth, Greater",
    "BreakableValue3": "Urns of Wealth, Superior",
    "CastBackstabTrait": "Parting Shot",
    "ChallengeSwitches1": "Plunder, Lesser",
    "ChallengeSwitches2": "Plunder, Greater",
    "ChallengeSwitches3": "Plunder, Superior",
    "ChamberStackTrait": "Pom Blossom",
    "ChaosBoonTrait": "Cosmic Egg",
    "Chariot": "Nemean Chariot",
    "ChariotSuicide": "Flame Wheel",
    "CodexBoonList": "Codex Index",
    "Cosmetic_Aquarium": "Aquarium, Cubical",
    "Cosmetic_BatCage": "Bat Cage, All-Seeing",
    "Cosmetic_CerberusBall": "Plaything, Round",
    "Cosmetic_CerberusBed": "Bedding, Quilted",
    "Cosmetic_CerberusBedA": "Bedding, Fancy",
    "Cosmetic_CerberusToy": "Plaything, Plush",
    "Cosmetic_CharonPillars": "Treasures, Boatman's",
    "Cosmetic_ClearFur": "Service, Deep Cleaning",
    "Cosmetic_ClearScratches": "Service, Detailing",
    "Cosmetic_DrapesBlue": "Drapery, Azure",
    "Cosmetic_DrapesGreen": "Drapery, Olive",
    "Cosmetic_DrapesGrey": "Drapery, Bone",
    "Cosmetic_HangingFood": "Meats, Cured",
    "Cosmetic_HouseCandles01": "Lighting, Dual Stick",
    "Cosmetic_HouseCandles02": "Lighting, Wax Pillar",
    "Cosmetic_HousePillars": "Columns, Divine",
    "Cosmetic_HousePillarsA": "Columns, Ominous",
    "Cosmetic_HousePillarsB": "Columns, Jeweled",
    "Cosmetic_KitchenIsland": "Kitchenette, Expanded",
    "Cosmetic_KitchenStoveCauldron": "Cauldron, Fiery",
    "Cosmetic_KitchenStoveFlame": "Fire Pit, Wood-Burning",
    "Cosmetic_Knives": "Cutlery, Kitchenette",
    "Cosmetic_LaurelsBlue": "Laurels, Cobalt",
    "Cosmetic_LaurelsSkulls": "Laurels, Deathly",
    "Cosmetic_LoungeAdditionalSeating": "Seating, Red Hide",
    "Cosmetic_LoungeBrokerRug": "Rug, Welcome",
    "Cosmetic_LoungeCakeDisplay": "Delicacy, Ambrosial",
    "Cosmetic_LoungeChairsA": "Seating, Olive",
    "Cosmetic_LoungeClayOven": "Oven, Kitchenette",
    "Cosmetic_LoungeDiscoBall": "Prism-Sphere, Revolving",
    "Cosmetic_LoungeDiscoBallA": "Prism-Sphere, Revolting",
    "Cosmetic_LoungeFireplace": "Fireplace, Burial",
    "Cosmetic_LoungeLiquor": "Shelf, Vintage",
    "Cosmetic_LoungePaintingSkelly": "Painting, Skeletal",
    "Cosmetic_LoungeRug": "Rug, Earthy",
    "Cosmetic_LoungeRugA": "Rug, Elysian",
    "Cosmetic_LoungeRugB": "Rug, Chthonic",
    "Cosmetic_LoungeRugC": "Rug, Sanguine",
    "Cosmetic_LoungeShortcut": "Shortcut, Great Hall",
    "Cosmetic_LoungeTablesA": "Tables, Serpentine",
    "Cosmetic_LoungeTreatJar": "Jar, Treat-Filled",
    "Cosmetic_MainHallBones": "Bonework, Ominous",
    "Cosmetic_MainHallCenterpieceA": "Insignia, Fated Order",
    "Cosmetic_MainHallCouch": "Chaise, Divine",
    "Cosmetic_MainHallFireplace": "Fireplace, Infernal",
    "Cosmetic_MainHallFireplaceA": "Fireplace, Nocturnal",
    "Cosmetic_MainHallFlowers": "Petals, Scattered",
    "Cosmetic_MainHallPetalFlyers": "Petals, Ever-Falling",
    "Cosmetic_MainHallPetals": "Petals, Shade-Strewn",
    "Cosmetic_MainHallSarcophagi": "Tombs, Royal",
    "Cosmetic_MainHallThroneA": "Throne, Hell-Hound",
    "Cosmetic_MainHallTikiTorches": "Flames, Promethean",
    "Cosmetic_MainHallTowels": "Towel Rack, Stygian",
    "Cosmetic_MusicPlayer": "Court Music Stand",
    "Cosmetic_NorthHallBust": "Bust, Old Man",
    "Cosmetic_NorthHallCouch": "Seating, Luxurious",
    "Cosmetic_NorthHallFountain": "Fountain, West Hall",
    "Cosmetic_NorthHallMirror": "Mirror, Guardpost",
    "Cosmetic_NorthHallPaintingAsphodel": "Landscape, Asphodel",
    "Cosmetic_NorthHallPaintingElysium": "Landscape, Elysium",
    "Cosmetic_NorthHallPaintingFury": "Painting, Fury Sisters",
    "Cosmetic_NorthHallPaintingHades": "Painting, God of the Dead",
    "Cosmetic_NorthHallPaintingMysteryGirl": "Portrait, Princess",
    "Cosmetic_NorthHallPaintingMysteryWoman": "Painting, Night",
    "Cosmetic_NorthHallPaintingTartarus": "Landscape, Tartarus",
    "Cosmetic_NorthHallPaintingTheseus": "Portrait, Exalted Hero",
    "Cosmetic_NorthHallPaintingTots": "Portrait, Cerberus",
    "Cosmetic_NorthHallPaintingZagreus": "Painting, Prince",
    "Cosmetic_NorthHallPedestalBust": "Sculpture, Bloodless",
    "Cosmetic_NorthHallPedestalMechanism": "Contraption, Intricate",
    "Cosmetic_NorthHallRug": "Rug, Earthy",
    "Cosmetic_NorthHallRugA": "Rug, Elysian",
    "Cosmetic_NorthHallRugB": "Rug, Chthonic",
    "Cosmetic_NorthHallRugC": "Rug, Sanguine",
    "Cosmetic_NorthHallSundial": "Sundial, Imported",
    "Cosmetic_NorthHallWarriorStatue": "Sculpture, Heroic",
    "Cosmetic_SeatCushions": "Seating, Covered",
    "Cosmetic_SkullFloorTiles": "Tiling, Skull",
    "Cosmetic_SouthHallFlowers": "Flower Vase, Lilac",
    "Cosmetic_SouthHallFlowersA": "Flower Vase, Rose",
    "Cosmetic_SouthHallFountain": "Fountain, East Wing",
    "Cosmetic_SouthHallMosaic": "Mosaic, Chthonic",
    "Cosmetic_SouthHallMosaicB": "Mosaic, Minoan",
    "Cosmetic_SouthHallTrimBrown": "Trim, Burnished Gold",
    "Cosmetic_SouthHallTrimGrey": "Trim, Ash Gray",
    "Cosmetic_SouthHallTrimPurple": "Trim, Chthonic Purple",
    "Cosmetic_SpiceRack": "Spice Rack, Kitchenette",
    "Cosmetic_WallWeaponAxe": "Decorative Arms, Labrys",
    "Cosmetic_WallWeaponBident": "Decorative Arms, Bident",
    "Cosmetic_WallWeaponSword": "Decorative Arms, Xiphos",
    "Crawler": "Crawler",
    "CrusherUnit": "Skull-Crusher",
    "CrusherUnitElite": "Dire Skull-Crusher",
    "CurseSickTrait": "Curse of Longing",
    "DeathArea": "House of Hades",
    "DemeterUpgrade": "Demeter",
    "DionysusAphroditeStackIncreaseTrait": "Low Tolerance",
    "DionysusUpgrade": "Dionysus",
    "DirectionalArmorTrait": "Myrmidon Bracer",
    "DisembodiedHand": "Wringer",
    "DislodgeAmmoTrait": "Aspect of Poseidon",
    "DistanceDamageTrait": "Distant Memory",
    "DusaAssistTrait": "Companion Fidi",
    "Elysium": "Elysium",
    "ElysiumReprieve": "Fountain Chamber, Elysium",
    "FastClearDodgeBonusTrait": "Lambent Plume",
    "Fish_Asphodel_Legendary_01": "Flameater",
    "Fish_Chaos_Common_01": "Mati",
    "Fish_Chaos_Legendary_01": "Voidskate",
    "Fish_Chaos_Rare_01": "Projelly",
    "Fish_Elysium_Legendary_01": "Seamare",
    "Fish_Styx_Legendary_01": "Stonewhal",
    "Fish_Surface_Legendary_01": "Sturgeon",
    "Fish_Tartarus_Legendary_01": "Scyllascion",
    "FishingUnlockItem": "Rod of Fishing",
    "FistDetonateTrait": "Aspect of Gilgamesh",
    "FistWeapon": "Twin Fists",
    "FistWeaveTrait": "Aspect of Demeter",
    "FlurrySpawner": "Soul Catcher",
    "FlurrySpawnerElite": "Dire Soul Catcher",
    "ForceAphroditeBoonTrait": "Eternal Rose",
    "ForceAresBoonTrait": "Blood-filled Vial",
    "ForceArtemisBoonTrait": "Adamant Arrowhead",
    "ForceAthenaBoonTrait": "Owl Pendant",
    "ForceDemeterBoonTrait": "Frostbitten Horn",
    "ForceDionysusBoonTrait": "Overflowing Cup",
    "ForcePoseidonBoonTrait": "Conch Shell",
    "ForceZeusBoonTrait": "Thunder Signet",
    "FreezeShotUnit": "Gorgon",
    "FuryAssistTrait": "Companion Battie",
    "GemDropRunProgress": "Gemstones, Brilliant",
    "GhostAdminDesk": "Contractor's Desk, Deluxe",
    "GiftDropRunProgress": "Nectar, Vintage",
    "GunGrenadeSelfEmpowerTrait": "Aspect of Eris",
    "GunLoadedGrenadeTrait": "Aspect of Lucifer",
    "GunManualReloadTrait": "Aspect of Hestia",
    "GunWeapon": "Adamant Rail",
    "HadesEMFight": "Extremer Measures",
    "HadesShoutKeepsake": "Sigil of the Dead",
    "HadesShoutTrait": "Hades' Aid",
    "Harpy": "Megaera, the Fury",
    "Harpy2": "Alecto",
    "Harpy3": "Tisiphone",
    "HealthFountainHeal1": "Underworld Fountains, Purified",
    "HealthFountainHeal2": "Underworld Fountains, Holy",
    "HeartsickCritDamageTrait": "Heart Rend",
    "HeavyMelee": "Wretched Thug",
    "HeavyMeleeElite": "Dire Thug",
    "HeavyRanged": "Brimstone",
    "HeavyRangedForked": "Snakestone",
    "HermesUpgrade": "Hermes",
    "HomingLaserTrait": "Crystal Clarity",
    "HouseBed01a": "Bedding, Chthonic",
    "HouseCouch02A": "Recliner, Fancy",
    "HouseDagger01": "Arms, Assorted",
    "HouseGamingTable01": "Table, Entertainment",
    "HouseLyre01": "Lyre, Splendid",
    "HousePoster01": "Wall-Scroll, Achilles",
    "HousePoster02": "Wall-Scroll, Aphrodite",
    "HousePoster05": "Wall-Scroll, Dionysus",
    "HouseRug03B": "Rug, Stately",
    "HouseWaterBowl01": "Pool, Scrying",
    "HouseWeights01": "Weights, Massive",
    "HydraHeadImmortal": "Bone Hydra",
    "IceStrikeArrayTrait": "Ice Wine",
    "ImpactBoltTrait": "Sea Storm",
    "ImprovedPomTrait": "Sweet Nectar",
    "JoltDurationTrait": "Cold Fusion",
    "LightRanged": "Wretched Witch",
    "LightRangedElite": "Dire Witch",
    "LightningCloudTrait": "Scintillating Feast",
    "LockKeyDropRunProgress": "Chthonic Keys, Fated",
    "LowHealthDamageTrait": "Skull Earring",
    "Minotaur": "Asterius",
    "NPC_Achilles_01": "Achilles",
    "NPC_FurySister_01": "Megaera",
    "NPC_Patroclus_01": "Patroclus",
    "NPC_Skelly_01": "Skelly",
    "NPC_Thanatos_01": "Thanatos",
    "NoLastStandRegenerationTrait": "Stubborn Roots",
    "NyxQuestItem": "Eldest Sigil Restoration",
    "OfficeDoorUnlockItem": "Administrative Privilege",
    "OlympianReunionQuestComplete": "Report to Persephone and Hades Afterward",
    "OrpheusEurydiceQuestItem": "Singer's Gamble",
    "OrpheusUnlockItem": "Court Musician's Sentence",
    "PerfectClearDamageBonusTrait": "Pierced Butterfly",
    "PoisonCritVulnerabilityTrait": "Splitting Headache",
    "PoisonTickRateTrait": "Curse of Nausea",
    "PoseidonAresProjectileTrait": "Curse of Drowning",
    "PoseidonUpgrade": "Poseidon",
    "PostBossGiftRack": "Keepsake Collection, Regional",
    "PunchingBagUnit": "Wretched Lout",
    "PunchingBagUnitElite": "Dire Lout",
    "QuestLog": "Fated List of Minor Prophecies",
    "RangedBurrower": "Dracon",
    "RaritySuperBoost": "Exclusive Access",
    "RatThug": "Gigantic Vermin",
    "RatThugMiniboss": "Dire Gigantic Vermin",
    "ReboundingAthenaCastTrait": "Lightning Phalanx",
    "RegeneratingCappedSuperTrait": "Smoldering Air",
    "ReincarnationTrait": "Lucky Tooth",
    "RoomRewardConsolationPrize": "Red Onion",
    "RoomRewardMetaPointDropRunProgress": "Darkness, Pitch-Black",
    "SatyrRanged": "Satyr Cultist",
    "SatyrRangedMiniboss": "Dire Satyr Cultist",
    "SelfLaserTrait": "Cold Embrace",
    "ShadeBowUnit": "Strongbow",
    "ShadeShieldUnit": "Greatshield",
    "ShadeSpearUnit": "Longspear",
    "ShadeSwordUnit": "Brightsword",
    "ShieldAfterHitTrait": "Broken Spearpoint",
    "ShieldBossTrait": "Evergreen Acorn",
    "ShieldLoadAmmoTrait": "Aspect of Beowulf",
    "ShieldRushBonusProjectileTrait": "Aspect of Chaos",
    "ShieldTwoShieldTrait": "Aspect of Zeus",
    "ShieldWeapon": "Shield of Chaos",
    "ShopDurationTrait": "Bone Hourglass",
    "ShrinePointGates": "Gateways, Erebus",
    "SisyphusAssistTrait": "Companion Shady",
    "SisyphusQuestItem": "Knave-King's Sentence",
    "SlowProjectileTrait": "Calculated Risk",
    "SpearSpinTravel": "Aspect of Guan Yu",
    "SpearTeleportTrait": "Aspect of Achilles",
    "SpearWeapon": "Eternal Spear",
    "SpearWeaveTrait": "Aspect of Hades",
    "SpikeTrap": "Spike Trap",
    "SplitShotUnit": "Splitter",
    "SpreadShotUnit": "Spreader",
    "StackUpgrade": "Pom of Power",
    "StationaryRiftTrait": "Freezing Vortex",
    "StatusImmunityTrait": "Unshakable Mettle",
    "Swarmer": "Numbskull",
    "SwarmerElite": "Dire Numbskull",
    "SwordBaseUpgradeTrait": "Aspect of Zagreus",
    "SwordConsecrationTrait": "Aspect of Arthur",
    "SwordCriticalParryTrait": "Aspect of Nemesis",
    "SwordWeapon": "Stygian Blade",
    "Tartarus": "Tartarus",
    "TartarusReprieve": "Fountain Chamber, Tartarus",
    "TemporaryBoonRarityTrait": "Yarn of Ariadne",
    "Thanatos": "Thanatos",
    "ThanatosAssistTrait": "Companion Mort",
    "Theseus": "Theseus",
    "ThiefImpulseMineLayer": "Bother",
    "ThiefMineLayer": "Wretched Pest",
    "TrialUpgrade": "Chaos",
    "TriggerCurseTrait": "Merciful End",
    "UnusedWeaponBonusAddGems": "Darker Thirst",
    "VanillaTrait": "Shattered Shackle",
    "ZeusUpgrade": "Zeus",
}
