"""Internal entity id -> friendly DisplayName for the viewer's
Other-Requirements value resolution (boons/traits, keepsakes, companions,
weapon aspects, god boons, enemies, cosmetics, items and more).

Vendored from Hades 2's ``Game/Text/en`` sjson DisplayName entries,
filtered to the ids that appear as ``otherRequirements`` operand values.
Regenerate with ``scripts/gen_entity_names.py --write`` after a data
refresh; the internal id is always kept in the row tooltip, so a missing
entry just falls back to showing the raw id.
"""

HADES2_ENTITY_NAMES = {
    "AllCloseBoon": "Island Getaway",
    "AmplifyConeBoon": "King Tide",
    "AphroditeUpgrade": "Aphrodite",
    "ApolloSecondStageCastBoon": "Glorious Disaster",
    "ApolloUpgrade": "Apollo",
    "ArachneAboutCurseQuest01": "Visit Arachne & Discuss What Transpired",
    "AresUpgrade": "Ares",
    "ArmorGainKeepsake": "Silken Sash",
    "AthenaEncounterKeepsake": "Gorgon Amulet",
    "AutoRevengeBoon": "Heinous Affront",
    "AutomatonBeamer": "Auto-Watcher",
    "AutomatonBeamer_Elite": "Auto-Watcher (Elite)",
    "AutomatonEnforcer": "Auto-Forcer",
    "AutomatonEnforcer_Elite": "Auto-Forcer (Elite)",
    "AxeArmCastAspect": "Aspect of Charon",
    "AxePerfectCriticalAspect": "Aspect of Thanatos",
    "AxeRallyAspect": "Aspect of Nergal",
    "BlindClearBoon": "Rude Awakening",
    "BlockDeathKeepsake": "Engraved Pin",
    "BloodManaBurstBoon": "Carnal Pleasure",
    "BloodRetentionBoon": "Universal Donor",
    "BonusMoneyKeepsake": "Gold Purse",
    "BossChronos02": "Behold Unrivaled Chronos",
    "BossDifficultyShrineUpgrade": "Vow of Rivals",
    "BossEris02": "Vanquish Unrivaled Strife",
    "BossHecate02": "Vanquish Unrivaled Hecate",
    "BossInfestedCerberus02": "Vanquish Unrivaled Cerberus",
    "BossMetaUpgradeKeepsake": "Crystal Figurine",
    "BossPolyphemus02": "Vanquish Unrivaled Polyphemus",
    "BossPreDamageKeepsake": "Knuckle Bones",
    "BossPrometheus02": "Vanquish Unrivaled Prometheus",
    "BossScylla02": "Vanquish Unrivaled Scylla",
    "BossTyphonHead02": "Behold Unrivaled Typhon",
    "BountyBoard": "Pitch-Black Stone",
    "Brawler": "Wastrel",
    "BreakExplosiveArmorBoon": "Volatile Coating",
    "BreakInvincibleArmorBoon": "Protective Coating",
    "BurnConsumeBoon": "Freezer Burn",
    "BurnRefreshBoon": "Burning Desire",
    "CardUpgradePoints": "Moon Dust",
    "CastHazardBoon": "Hazard Boom",
    "CatFamiliar": "Toula",
    "CharmCrowdBoon": "Ecstatic Obsession",
    "CharonPoints": "Obol Points",
    "Chronos": "Chronos",
    "CirceEnlargeTrait": "Word of Greater Girth",
    "CirceShrinkTrait": "Word of Smaller Stature",
    "ClearRootBoon": "Cryo Pounder",
    "Cosmetic_AmbientDogs": "Habitat, Canine",
    "Cosmetic_ArachneTapestry": "Tapestry, Silken",
    "Cosmetic_AsteriusPlush": "Plush, Bull of Minos",
    "Cosmetic_Cauldron01a": "Cauldron, Astral",
    "Cosmetic_Cauldron01b": "Cauldron, Python",
    "Cosmetic_CollectableArtemis": "Chthonic Chid, Artemis",
    "Cosmetic_CollectableCharon": "Chthonic Chid, Charon",
    "Cosmetic_CollectableDora": "Chthonic Chid, Dora",
    "Cosmetic_CollectableEris": "Chthonic Chid, Eris",
    "Cosmetic_CollectableHecate": "Chthonic Chid, Hecate",
    "Cosmetic_CollectableHypnos": "Chthonic Chid, Hypnos",
    "Cosmetic_CollectableIcarus": "Chthonic Chid, Icarus",
    "Cosmetic_CollectableMoros": "Chthonic Chid, Moros",
    "Cosmetic_CollectableNemesis": "Chthonic Chid, Nemesis",
    "Cosmetic_CollectableOdysseus": "Chthonic Chid, Odysseus",
    "Cosmetic_CollectableSelene": "Chthonic Chid, Selene",
    "Cosmetic_CollectableSkelly": "Chthonic Chid, Schelemeus",
    "Cosmetic_DoraBench02": "Bench, Haunted",
    "Cosmetic_DreamRug": "Rug, Hypnotic",
    "Cosmetic_ErisRug": "Rug, Tri-Wing",
    "Cosmetic_ErisTrashcan": "Basket, Rubbish",
    "Cosmetic_ErisWarningSign01": "Warning Sign, Strife",
    "Cosmetic_FanPoster01": "Wall-Scroll, Scylla",
    "Cosmetic_FanPoster01b": "Wall-Scroll, Heracles",
    "Cosmetic_HypnosStatue": "Bust, Hypnos",
    "Cosmetic_IcarusTable01": "Workbench, Artisan's",
    "Cosmetic_MorosChaise": "Recliner, Fateful",
    "Cosmetic_MorosRug": "Rug, Fateful",
    "Cosmetic_MorosScrolls": "Parchments, Fateful",
    "Cosmetic_MorosSpools": "Threads, Fateful",
    "Cosmetic_MorosTentCanopy": "Draping, Fateful",
    "Cosmetic_MorosTerrain": "Cobblestones, Fateful",
    "Cosmetic_NemesisChair": "Throne, Chthonic",
    "Cosmetic_OdysseusTable01a": "War Table, Grecian",
    "Cosmetic_Poppies": "Flowerbed, Poppy",
    "Cosmetic_SkellyFloor01c": "Dais, Hypnotic",
    "Cosmetic_StarJar": "Receptacle, Shiny Star",
    "Cosmetic_ThanCutout": "Standee, Thanatos",
    "Cosmetic_TrainingDummy01c": "Effigies, Hypnotic",
    "CosmeticsPoints": "Kudos",
    "CoverRegenerationBoon": "Warm Breeze",
    "CritBonusBoon": "Pressure Points",
    "DaggerBlockAspect": "Aspect of Artemis",
    "DaggerHomingThrowAspect": "Aspect of Pan",
    "DaggerTripleAspect": "Aspect of the Morrigan",
    "DamagedDamageBoostKeepsake": "Blackened Fleece",
    "DashOmegaBuffBoon": "Shadow Pounce",
    "DeathVengeanceKeepsake": "Evil Eye",
    "DecayingBoostKeepsake": "Lion Fang",
    "DemeterUpgrade": "Demeter",
    "DoorHealReserveKeepsake": "Ghost Onion",
    "DoorReroll": "The Enchantress",
    "DoorRerollMetaUpgrade": "The Enchantress",
    "DoubleMassiveAttackBoon": "Chain Reaction",
    "DoubleRewardBoon": "Sea Star",
    "DoubleSplashBoon": "Arterial Spray",
    "DoubleSwordBoon": "Cutting Edge",
    "DreamPoints": "Shiny Stars",
    "Eagle": "Aetos",
    "EasyMode": "God Mode",
    "EchoBurnBoon": "Thermal Dynamics",
    "ElementalHealthBoon": "Water Fitness",
    "EncounterStartOffenseBuffBoon": "Hydraulic Might",
    "Eris": "Eris",
    "EscalatingKeepsake": "Discordant Bell",
    "FamiliarCostume_CatChaos": "Chaotic",
    "FamiliarCostume_FrogHell": "Draconic",
    "FamiliarCostume_HoundCute": "Grecian",
    "FamiliarCostume_PolecatMoon": "Moon-Touched",
    "FamiliarCostume_RavenHell": "Phoenix",
    "FamiliarPoints": "Witch's Delight",
    "FireballRendBoon": "Fourth Degree",
    "FirstHitHealTrait": "Breath of Eros",
    "FishPLegendary": "Starsailor",
    "FishQLegendary": "Chimaerid",
    "FishQRare": "Stormgullet",
    "FocusAttackDamageTrait": "Ingenious Strike",
    "FocusCritBoon": "Killing Stroke",
    "FocusDamageShaveBoon": "High Surf",
    "FocusSpecialDamageTrait": "Ingenious Flourish",
    "FogEmitter_Elite": "Shadow-Spiller (Elite)",
    "ForceAphroditeBoonKeepsake": "Beautiful Mirror",
    "ForceApolloBoonKeepsake": "Harmonic Photon",
    "ForceAresBoonKeepsake": "Sword Hilt",
    "ForceDemeterBoonKeepsake": "Barley Sheaf",
    "ForceHephaestusBoonKeepsake": "Adamant Shard",
    "ForceHeraBoonKeepsake": "Iridescent Fan",
    "ForceHestiaBoonKeepsake": "Everlasting Ember",
    "ForcePoseidonBoonKeepsake": "Vivid Sea",
    "ForceZeusBoonKeepsake": "Cloud Bangle",
    "FountainRarityKeepsake": "Aromatic Phial",
    "FrogFamiliar": "Frinos",
    "GemPoints": "Gemstones",
    "GiftPoints": "Nectar",
    "GiftPointsEpic": "Twin Lures",
    "GiftPointsRare": "Bath Salts",
    "GodModeTrait": "Deus Ex Machina",
    "GoldifyKeepsake": "Time Piece",
    "GoodStuffBoon": "Natural Selection",
    "Guard": "Whisper",
    "HadesAndPersephoneKeepsake": "Jeweled Pom",
    "HadesCastProjectileBoon": "Howling Soul",
    "HadesChronosDebuffBoon": "Deep Dissent",
    "HadesDashSweepBoon": "Gigaros Dash",
    "HadesDeathDefianceDamageBoon": "Last Gasp",
    "HadesInvisibilityRetaliateBoon": "Unseen Ire",
    "HadesLifestealBoon": "Life Tax",
    "HadesManaUrnBoon": "Cinerary Circle",
    "HadesPreDamageBoon": "Old Grudge",
    "HadesSpearPoints": "Gigaros",
    "HarpyCutter": "Harpy Talon",
    "HarpyCutter_Elite": "Harpy Talon (Elite)",
    "HarpyDropper": "Harpy Raptor",
    "HarpyDropper_Elite": "Harpy Raptor (Elite)",
    "HealingReductionShrineUpgrade": "Vow of Scars",
    "Hecate": "Hecate",
    "HecateFishing02": "Seek to Know She Who Trained You",
    "HephaestusUpgrade": "Hephaestus",
    "HeraUpgrade": "Hera",
    "Heracles": "Heracles",
    "HermesUpgrade": "Hermes",
    "HestiaUpgrade": "Hestia",
    "HighHealthCritBoon": "Vital Signs",
    "HoundFamiliar": "Hecuba",
    "InfestedCerberus": "Infernal Beast",
    "InsideCastCritBoon": "Lethal Snare",
    "KeepsakeLevelBoon": "Cherished Heirloom",
    "LaserApolloTalent": "Shine of Apollo",
    "LeapHephaestusTalent": "Hand of Hephaestus",
    "LightningVulnerabilityBoon": "Killer Current",
    "LobCloseAttackAspect": "Aspect of Medea",
    "LobGunAspect": "Aspect of Hel",
    "LobImpulseAspect": "Aspect of Persephone",
    "LowHealthCritKeepsake": "White Antler",
    "Mage": "Casket",
    "ManaBurstCountBoon": "Sunny Disposition",
    "ManaOverTimeRefundKeepsake": "Silver Wheel",
    "ManaRestoreDamageBoon": "Incandescent Aura",
    "ManaShieldBoon": "Brave Face",
    "MassiveCastBoon": "Seismic Servo",
    "MaxHealthDamageBoon": "Hearty Appetite",
    "MemPointsCommon": "Psyche",
    "MetaCardPointsCommon": "Ashes",
    "MetaCardPointsCommonDrop": "Ashes",
    "MetaCurrency": "Bones",
    "MetaFabric": "Fate Fabric",
    "MeteorHestiaTalent": "Hearth of Hestia",
    "MiniBossCharybdis": "Charybdis",
    "MiniBossFogEmitter": "Shadow-Spiller",
    "MiniBossTreant": "Root-Stalker",
    "Mixer5Common": "Star Dust",
    "Mixer6Common": "Darkness",
    "MixerFBoss": "Cinder",
    "MixerGBoss": "Pearl",
    "MixerIBoss": "Zodiac Sand",
    "MixerMythic": "Entropy",
    "MixerOBoss": "Golden Apple",
    "MixerQBoss": "Void Lens",
    "Money": "Gold Crowns",
    "MoneyDamageBoon": "Ripple Effect",
    "MoonBeamAresTalent": "Lance of Ares",
    "MorosFirstMeeting": "Summon Moros Once More & Speak with Him",
    "MorosPostTrueEnding02": "Investigate the Underworld & Olympus",
    "NPC_Arachne_01": "Arachne",
    "NPC_Artemis_01": "Artemis",
    "NPC_Artemis_Field_01": "Artemis",
    "NPC_Athena_01": "Athena",
    "NPC_Bouldy_01": "Strange Rock",
    "NPC_Charon_01": "Charon",
    "NPC_Chronos_01": "Chronos",
    "NPC_Chronos_02": "Chronos",
    "NPC_Circe_01": "Circe",
    "NPC_Dionysus_01": "Dionysus",
    "NPC_Dora_01": "Dora",
    "NPC_Echo_01": "Echo",
    "NPC_Eris_01": "Eris",
    "NPC_Hades_Field_01": "Hades",
    "NPC_Hecate_01": "Hecate",
    "NPC_Heracles_01": "Heracles",
    "NPC_Hypnos_01": "Hypnos",
    "NPC_Icarus_01": "Icarus",
    "NPC_Medea_01": "Medea",
    "NPC_Moros_01": "Moros",
    "NPC_Narcissus_01": "Narcissus",
    "NPC_Nemesis_01": "Nemesis",
    "NPC_Nyx_Story_01": "Nyx",
    "NPC_Odysseus_01": "Odysseus",
    "NPC_Persephone_01": "Persephone",
    "NPC_Skelly_01": "Schelemeus",
    "NPC_Zeus_Story_01": "Zeus",
    "NemesisRandomEvent": "Nemesis",
    "NemesisShopping": "Nemesis",
    "OdysseusLooseEndsQuestComplete01": "Discuss the Outcome with Odysseus",
    "OmegaCastVolleyBoon": "Easy Shot",
    "OmegaExplodeBoon": "Explosive Intent",
    "OmegaPoseidonProjectileBoon": "Ocean Swell",
    "OreFSilver": "Silver",
    "OreNBronze": "Bronze",
    "OrePAdamant": "Adamant",
    "PackageBountyAres": "Trial of Slaughter",
    "PackageBountyChaos": "Trial of Destiny",
    "PackageBountyChaosIntro": "Trial of Origin",
    "PackageBountyDemeter": "Trial of the Fall",
    "PackageBountyHecate": "Trial of the Maiden",
    "PackageBountyHellChop": "Trial of Brawn",
    "PackageBountyHera": "Trial of Glory",
    "PackageBountyHestia": "Trial of Flame",
    "PackageBountyOceanus": "Trial of Salt",
    "PackageBountyPolyphemus": "Trial of the Flock",
    "PackageBountyRandomSurface_Difficulty1": "Chaos Above",
    "PackageBountyRandomSurface_Difficulty2": "Great Chaos Above",
    "PackageBountyRandomUnderworld_Difficulty1": "Chaos Below",
    "PackageBountyRandomUnderworld_Difficulty2": "Great Chaos Below",
    "PackageBountyRevenge": "Trial of Vengeance",
    "PackageBountySpellCast": "Trial of the Moon",
    "PackageBountyStarter": "Trial of Humility",
    "PackageBountySuitLegendary": "Trial of the Supreme",
    "PackageBountyZeus": "Trial of Thunder",
    "PlantFMoly": "Moly",
    "PlantFNightshade": "Nightshade",
    "PlantFNightshadeSeed": "Nightshade Seeds",
    "PlantGCattail": "Cattail",
    "PlantGCattailSeed": "Cattail Seeds",
    "PlantGLotus": "Lotus",
    "PlantHMyrtle": "Myrtle",
    "PlantHWheat": "Wheat",
    "PlantHWheatSeed": "Wheat Seeds",
    "PlantIPoppy": "Poppy",
    "PlantIPoppySeed": "Poppy Seeds",
    "PlantIShaderot": "Shaderot",
    "PlantNGarlic": "Garlic",
    "PlantNGarlicSeed": "Garlic Cloves",
    "PlantNMoss": "Moss",
    "PlantOMandrake": "Mandrake Root",
    "PlantOMandrakeSeed": "Mandrake Seeds",
    "PlantPIris": "Iris",
    "PlantPOlive": "Olive",
    "PlantPOliveSeed": "Olive Branch",
    "PlantQSnakereedSeed": "Plankton",
    "PolecatFamiliar": "Gale",
    "PolymorphZeusTalent": "Temper of Zeus",
    "Polyphemus": "Polyphemus",
    "PoseidonCastBoon": "Tidal Ring",
    "PoseidonExCastBoon": "Geyser Spout",
    "PoseidonManaBoon": "Flood Gain",
    "PoseidonSpecialBoon": "Wave Flourish",
    "PoseidonSplashSprintBoon": "Beach Ball",
    "PoseidonSprintBoon": "Breaker Rush",
    "PoseidonStatusBoon": "Slippery Slope",
    "PoseidonUpgrade": "Poseidon",
    "PoseidonWeaponBoon": "Wave Strike",
    "PotionPoseidonTalent": "Pride of Poseidon",
    "Prometheus": "Prometheus",
    "QuestBeatHecateWithoutArcana": "Natural Talent",
    "QuestCatchFish": "Denizens of the Depths",
    "QuestChaosKeepsakeFullRun": "Born to Win",
    "QuestMeetOlympians": "Family in Need",
    "QuestRescueFates": "Melinoë, Help Us",
    "Radiator": "Spindle",
    "RaiseDeadBoon": "Sun Worshiper",
    "RandomBlessingKeepsake": "Transcendent Embryo",
    "RapidSwordBoon": "Coffin Nail",
    "RarifyKeepsake": "Calling Card",
    "RavenFamiliar": "Raki",
    "ReboundingSparkBoon": "Master Conductor",
    "ReincarnationKeepsake": "Luckier Tooth",
    "ReserveManaHitShieldBoon": "Snow Queen",
    "RoomRewardBonusBoon": "Buried Treasure",
    "RootStrikeBoon": "Hail Storm",
    "SatyrCrossbow": "Satyr Champion",
    "SatyrCrossbow2": "Satyr Raider",
    "SatyrCrossbow2_Elite": "Satyr Raider (Elite)",
    "SatyrCultist": "Satyr Supplicant",
    "SatyrCultist_Elite": "Satyr Supplicant (Elite)",
    "SatyrLancer": "Satyr Hoplite",
    "SatyrLancer2": "Satyr Goldpike",
    "SatyrLancer2_Elite": "Satyr Goldpike (Elite)",
    "SatyrLancer_Elite": "Satyr Hoplite (Elite)",
    "SatyrRatCatcher": "Satyr Vierophant",
    "SatyrRatCatcher_Elite": "Satyr Vierophant (Elite)",
    "SatyrRatCatcher_Miniboss": "The Verminancer",
    "SatyrSapper": "Satyr Sapper",
    "SatyrSapper_Elite": "Satyr Sapper (Elite)",
    "Scylla": "Scylla",
    "SeedMystery": "Mystery Seeds",
    "SelfCastBoon": "Hostile Environment",
    "SentryBot": "Auto-Seeker",
    "SentryBot_Elite": "Auto-Seeker (Elite)",
    "ShowGameplayTimer": "Timer Display",
    "Shrine": "Oath of the Unseen",
    "SiegeVine": "Thorn-Weeper",
    "SiegeVine_Elite": "Thorn-Weeper (Elite)",
    "SkipEncounterKeepsake": "Fig Leaf",
    "SlamManaBurstBoon": "Love Handles",
    "SorceryRegenMetaUpgrade": "The Moon",
    "SorceryRegenUpgrade": "The Moon",
    "SpellDrop": "Selene",
    "SpellLaserTrait": "Lunar Ray",
    "SpellLeapTrait": "Wolf Howl",
    "SpellMeteorTrait": "Total Eclipse",
    "SpellMoonBeamTrait": "Sky Fall",
    "SpellPolymorphTrait": "Twilight Curse",
    "SpellPotionTrait": "Moon Water",
    "SpellSummonTrait": "Night Bloom",
    "SpellTalentKeepsake": "Moon Beam",
    "SpellTimeSlowTrait": "Phase Shift",
    "SpellTransformTrait": "Dark Side",
    "SprintEchoBoon": "Romantic Spark",
    "StackUpgrade": "Pom of Power",
    "StaffClearCastAspect": "Aspect of Circe",
    "StaffRaiseDeadAspect": "Aspect of Anubis",
    "StaffSelfHitAspect": "Aspect of Momus",
    "SteamBoon": "Scalding Vapor",
    "StormSpawnBoon": "Tropical Cyclone",
    "SuitComboAspect": "Aspect of Shiva",
    "SuitHexAspect": "Aspect of Selene",
    "SuitMarkCritAspect": "Aspect of Nyx",
    "SummonHeraTalent": "Nurture of Hera",
    "SuperGiftPoints": "Ambrosia",
    "SuperSacrificeBoonHera": "Queen's Ransom",
    "SuperSacrificeBoonZeus": "King's Ransom",
    "SupplyDropBoon": "Supply Chain",
    "SupportingFireBoon": "Support Fire",
    "SurfacePenalty": "Chthonic Fate",
    "SurfaceShop": "Shrine of Hermes",
    "TalentDrop": "Path of Stars",
    "Talos": "Talos",
    "TempHammerKeepsake": "Experimental Hammer",
    "TemporaryForcedSecretDoorTrait": "Spark of Ixion",
    "TimeSlowDemeterTalent": "Squall of Demeter",
    "TimedBuffKeepsake": "Metallic Droplet",
    "TimedCritVulnerabilityBoon": "Death Warrant",
    "ToolExorcismBook": "Tablet of Peace",
    "ToolFishingRod": "Rod of Fishing",
    "ToolFishingRod2": "Rod of Fishing",
    "ToolPickaxe": "Crescent Pick",
    "ToolShovel": "Silver Spade",
    "TorchAutofireAspect": "Aspect of Supay",
    "TorchDetonateAspect": "Aspect of Moros",
    "TorchSprintRecallAspect": "Aspect of Eos",
    "TransformAphroditeTalent": "Allure of Aphrodite",
    "TrashPoints": "Rubbish",
    "Treant": "Root-Stalker",
    "TrialUpgrade": "Chaos",
    "TyphonHead": "Typhon",
    "UnpickedBoonKeepsake": "Concave Stone",
    "UnusedWeaponBonusTrait": "Grave Thirst",
    "UnusedWeaponBonusTrait2": "Gravest Thirst",
    "WeaponAxe": "Moonstone Axe",
    "WeaponDagger": "Sister Blades",
    "WeaponLob": "Argent Skull",
    "WeaponPointsRare": "Nightmare",
    "WeaponStaffSwing": "Witch's Staff",
    "WeaponSuit": "Black Coat",
    "WeaponTorch": "Umbral Flames",
    "WeaponUpgrade": "Daedalus Hammer",
    "WellShop": "Well of Charon",
    "WorldUpgradeAltRunDoor": "Permeation of Witching-Wards",
    "WorldUpgradeBathHouse": "Rite of Vapor-Cleansing",
    "WorldUpgradeBountyBoard": "Abyssal Insight",
    "WorldUpgradeCardUpgradePoints2": "Moonlit Essence from Stars",
    "WorldUpgradeCardUpgradeSystem": "Consecration of Ashes",
    "WorldUpgradeDoraMemory": "Return of Latent Memories",
    "WorldUpgradeFamiliarCostumeSystem": "Alteration of Familiar Forms",
    "WorldUpgradeFamiliarSystem": "Faith of Familiar Spirits",
    "WorldUpgradeFamiliarUpgradeSystem": "Bravery of Familiar Spirits",
    "WorldUpgradeFieldsRewardFinder": "Reviving a Mournful Husk",
    "WorldUpgradeFishingPoint": "Rite of River-Fording",
    "WorldUpgradeGameStats": "Summoning of Personal Insights",
    "WorldUpgradeGarden": "Flourishing Soil",
    "WorldUpgradeGardenT3": "Verdant Soil",
    "WorldUpgradeMarket": "Summoning of Mercantile Fortune",
    "WorldUpgradeMedeaTears": "Essence of Sorrow",
    "WorldUpgradeMorosUnlock": "Doomed Beckoning",
    "WorldUpgradeMusicPlayer": "Summoning of Musical Rhapsody",
    "WorldUpgradeNarcissusWaters": "Purification of Crystal Clarity",
    "WorldUpgradeNectar": "Sweet Nectar",
    "WorldUpgradePauseChronosFight": "Power to Pause and Reflect",
    "WorldUpgradeQuestLog": "Fated Intervention",
    "WorldUpgradeRunHistory": "Summoning of Historic Travails",
    "WorldUpgradeShadeMercs": "Necromantic Influence",
    "WorldUpgradeSkellyHealth": "Augmentation of Bone Density",
    "WorldUpgradeStormStop": "Disintegration of Monstrosity",
    "WorldUpgradeStoryReset": "Returning to a Real Possibility",
    "WorldUpgradeSurfacePenaltyCure": "Unraveling a Fateful Bond",
    "WorldUpgradeSurfaceShops": "Rush of Fresh Air",
    "WorldUpgradeTaverna": "Rite of Social Solidarity",
    "WorldUpgradeTimeSlowChronosFight": "Temporal Fluctuation",
    "WorldUpgradeTimeStop": "Dissolution of Time",
    "WorldUpgradeToolsShop": "Night's Craftwork",
    "WorldUpgradeUnusedWeaponBonus": "Gathering of Ancient Bones",
    "WorldUpgradeWakeHypnos": "End to Deepest Slumber",
    "WorldUpgradeWakeHypnosT2": "End to Dearest Slumber",
    "WorldUpgradeWakeHypnosT3": "End to Dumbest Slumber",
    "WorldUpgradeWeaponUpgradeSystem": "Aspects of Night and Darkness",
    "WorldUpgradeWellShops": "Rise of Stygian Wells",
    "Zagreus": "Zagreus",
    "ZeusUpgrade": "Zeus",
    "ZombieOlympus": "Snow-Shambler",
}
